/**
 * POST /api/email/inbound
 *
 * Inbound email webhook handler.
 * Users can email their Pivot questions and get AI responses.
 * Can be connected to SendGrid/Mailgun/Postmark inbound parsing.
 *
 * Example: user emails ask@pivot-bi.com with "What's my MRR?"
 * → Pivvy responds with the answer via reply email.
 */

import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    // Support multiple inbound email services
    const from = body.from ?? body.sender ?? body.From ?? body.envelope?.from;
    const subject = body.subject ?? body.Subject ?? "";
    const text = body.text ?? body["stripped-text"] ?? body.TextBody ?? body.body ?? "";
    const html = body.html ?? body.HtmlBody ?? "";

    if (!from || !text) {
      return NextResponse.json({ error: "Missing from or text" }, { status: 400 });
    }

    // Extract email address
    const emailMatch = from.match(/[\w.-]+@[\w.-]+\.\w{2,}/);
    const email = emailMatch?.[0]?.toLowerCase();
    if (!email) {
      return NextResponse.json({ error: "Invalid from address" }, { status: 400 });
    }

    // Find org by user email
    const supabase = createAdminClient();
    const { data: profile } = await supabase
      .from("profiles")
      .select("id, organization_id")
      .eq("email", email)
      .maybeSingle();

    if (!profile?.organization_id) {
      console.warn("[Email Inbound] No org found for email:", email);
      return NextResponse.json({ ok: true, message: "User not found" });
    }

    const orgId = profile.organization_id;

    // Process in background
    processEmailQuery(orgId, email, subject, text).catch(err =>
      console.error("[Email Inbound] Processing error:", err)
    );

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("[Email Inbound]", err);
    return NextResponse.json({ error: "Processing failed" }, { status: 500 });
  }
}

async function processEmailQuery(
  orgId: string,
  userEmail: string,
  subject: string,
  text: string,
): Promise<void> {
  // Route to Pivvy
  const { runBusinessAgent } = await import("@/lib/agent/business-agent");
  const message = subject ? `${subject}: ${text}` : text;

  const result = await runBusinessAgent({
    orgId,
    messages: [],
    message: message.slice(0, 2000),
  });

  const reply = result.message ?? "I couldn't process your request.";

  // Send reply email
  try {
    const { globalRegistry, createCostTracker } = await import("@/lib/execution/tools/index");
    await globalRegistry.execute("send_email", {
      to: userEmail,
      subject: `Re: ${subject || "Your Pivot Question"}`,
      body: `${reply}\n\n---\nThis response was generated by Pivvy, your Pivot AI advisor.\nReply to this email to continue the conversation.`,
    }, {
      orgId,
      agentId: "pivvy",
      sessionId: "email-bot",
      costTracker: createCostTracker(0.10),
    });
  } catch (err) {
    console.error("[Email Inbound] Failed to send reply:", err);
  }
}
